language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

env:
  global:
    - MPLBACKEND=agg

matrix:
  fast_finish: true
  include:
    - python: 3.5
    - python: 3.6
    - python: nightly
  allow_failures:
    - python: nightly


install:
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade codecov coverage pytest
  - python -m pip install -r test_requirements.txt
  - python -m pip install -ve .

script:
  - pytest --cov=mplaltair --mpl
  - coverage report -m
  - set -e
  - codecov
