import matplotlib
import altair

from ._convert import _convert

def convert(spec):
    """Convert an altair encoding to a Matplotlib figure


    Parameters
    ----------
    spec
        The Vega-lite schema of the plot generated by Altair.

    Returns
    -------
    mapping : dict
        Mapping from parts of the encoding to the Matplotlib artists.  This is
        for later customization.


    """
    return _convert(spec)
