import matplotlib
import altair
import matplotlib.pyplot as plt
from ._convert import _convert
from ._data import _normalize_data
from ._axis import convert_axis
from ._marks import _handle_line


def convert(chart):
    """Convert an altair encoding to a Matplotlib figure


    Parameters
    ----------
    chart
        The Altair chart object generated by Altair

    Returns
    -------
    mapping : dict
        Mapping from parts of the encoding to the Matplotlib artists.  This is
        for later customization.


    """

    fig, ax = plt.subplots()
    _normalize_data(chart)

    if chart.mark in ['point', 'circle', 'square']:  # scatter
        mapping = _convert(chart)
        ax.scatter(**mapping)
    elif chart.mark == 'line':  # line
        _handle_line(chart, ax)
    else:
        raise NotImplementedError

    convert_axis(ax, chart)
    fig.tight_layout()

    return fig, ax
